# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_system.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66ile_system.proto\"5\n\rUploadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\"#\n\x0eUploadResponse\x12\x11\n\tchunk_ids\x18\x01 \x03(\t\"$\n\x0f\x44ownloadRequest\x12\x11\n\tchunk_ids\x18\x01 \x03(\t\"5\n\x10\x44ownloadResponse\x12!\n\tlocations\x18\x01 \x03(\x0b\x32\x0e.ChunkLocation\"8\n\rChunkLocation\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x15\n\rstorage_nodes\x18\x02 \x03(\t2p\n\nFileSystem\x12-\n\nUploadFile\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12\x33\n\x0c\x44ownloadFile\x12\x10.DownloadRequest\x1a\x11.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADREQUEST']._serialized_start=21
  _globals['_UPLOADREQUEST']._serialized_end=74
  _globals['_UPLOADRESPONSE']._serialized_start=76
  _globals['_UPLOADRESPONSE']._serialized_end=111
  _globals['_DOWNLOADREQUEST']._serialized_start=113
  _globals['_DOWNLOADREQUEST']._serialized_end=149
  _globals['_DOWNLOADRESPONSE']._serialized_start=151
  _globals['_DOWNLOADRESPONSE']._serialized_end=204
  _globals['_CHUNKLOCATION']._serialized_start=206
  _globals['_CHUNKLOCATION']._serialized_end=262
  _globals['_FILESYSTEM']._serialized_start=264
  _globals['_FILESYSTEM']._serialized_end=376
# @@protoc_insertion_point(module_scope)
